DROP TABLE IF EXISTS prices;

CREATE TABLE prices (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        brand_id INT NOT NULL,
                        start_date TIMESTAMP NOT NULL,
                        end_date TIMESTAMP NOT NULL,
                        price_list INT NOT NULL,
                        product_id INT NOT NULL,
                        priority INT NOT NULL,
                        price DECIMAL NOT NULL,
                        curr VARCHAR NOT NULL
);